local_backend: true # Set to true if you want to use the local backend for local development

# For local development run:
# npm run preview
# and in a separate terminal run:
# npx netlify-cms-proxy-server

# More instructions in README.md

site_url: https://cforp-platonic-lwapp-test.azurewebsites.net # URL of your site without trailing slash
display_url: https://cforp-platonic-lwapp-test.azurewebsites.net # URL of your site for og:image without trailing slash

backend:
  name: github # Use github for deployment using github auth
  repo: centrefranco/platonic # Path to your GitHub repository
  branch: test # Branch to update (optional; defaults to master)
  base_url: https://cforp-decap-oauth.onrender.com # Path to ext auth provider # *** New sites must be whitelisted in auth app CORS origin. ***

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - name: 'settings'
    label: 'Settings'
    label_singular: 'Setting'
    files:
      - label: 'Meta Information & General Settings'
        name: 'site'
        file: 'src/content/_settings/general.yml'
        fields:
          - {
              label: 'Site Title',
              name: 'title',
              widget: 'string',
              i18n: true,
              required: false,
            }
          - {
              label: 'Site Description',
              name: 'description',
              widget: 'text',
              i18n: true,
              required: false,
            }
          - {
              label: 'Site URL (Production)',
              name: 'url',
              widget: 'string',
              i18n: true,
              required: false,
            }
          - {
              label: 'Site Image (1200px × 630px)',
              name: 'previewImage',
              widget: 'image',
              i18n: true,
              required: false,
            }
          - {
              label: 'Favicon (filename must start with favicon)',
              name: 'favicon',
              widget: 'image',
              i18n: true,
              required: false,
            }
          - {
              label: 'Google Analytics Code',
              name: 'gaCode',
              widget: 'string',
              i18n: true,
              required: false,
            }
      - label: 'Social Settings'
        name: 'social'
        file: 'src/content/_settings/social.yml'
        fields:
          - {
              label: 'Facebook URL',
              name: 'facebook',
              widget: 'string',
              i18n: true,
              required: false,
            }
          - {
              label: 'X URL',
              name: 'x',
              widget: 'string',
              i18n: true,
              required: false,
            }
          - {
              label: 'Instagram URL',
              name: 'instagram',
              widget: 'string',
              i18n: true,
              required: false,
            }
          - {
              label: 'Linkedin',
              name: 'linkedin',
              widget: 'string',
              i18n: true,
              required: false,
            }

  - label: 'Pages'
    label_singular: 'Page'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'src/content/pages/home.yml'
        fields:
          - label: 'Title'
            name: 'title'
            required: false
            widget: 'text'
          - label: 'Content'
            name: 'content'
            required: false
            widget: 'list'
            types:
              # Text
              - label: 'Text'
                name: 'textBlock'
                widget: 'object'
                summary: '{{fields.text}}' # Preview text in /admin
                fields:
                  - label: 'Text'
                    name: 'text'
                    widget: 'text'
                    required: false

              # Formatted Text
              - label: 'Formatted Text'
                name: 'formattedTextBlock'
                widget: 'object'
                summary: '{{fields.formattedText}}'
                fields:
                  - label: 'Formatted Text'
                    name: 'formattedText'
                    widget: 'formatted-text'
                    required: false

              # Rich Text
              - label: 'Rich Text'
                name: 'richTextBlock'
                widget: 'object'
                summary: '{{fields.text}}' # Preview text in /admin
                fields:
                  - label: 'Rich Text'
                    name: 'richText'
                    widget: 'markdown'
                    required: false

              # Image
              - label: 'Image'
                name: 'imageBlock'
                widget: 'object'
                summary: '{{fields.alt}}' # Preview text in /admin
                fields:
                  - label: 'Image'
                    name: 'image'
                    widget: 'image'
                    media_library:
                      config:
                        multiple: false
                  - label: 'Alt Text'
                    name: 'alt'
                    widget: 'string'
                    required: false
                  - label: 'Attribution'
                    name: 'attribution'
                    widget: 'text'
                    required: false

      - label: 'About Page'
        name: 'about'
        # Configure i18n to true at file level required for file collection.
        file: 'src/content/pages/about.yml'
        fields:
          - label: 'Title'
            name: 'title'
            required: false
            widget: 'text'
          - label: 'Content'
            name: 'content'
            required: false
            widget: 'list'
            types:
              # Text
              - label: 'Text'
                name: 'textBlock'
                widget: 'object'
                summary: '{{fields.text}}'
                fields:
                  - label: 'Text'
                    name: 'text'
                    widget: 'text'
                    required: false

              # Formatted Text
              - label: 'Formatted Text'
                name: 'formattedTextBlock'
                widget: 'object'
                summary: '{{fields.formattedText}}'
                fields:
                  - label: 'Formatted Text'
                    name: 'formattedText'
                    widget: 'formatted-text'
                    required: false

              # Rich Text
              - label: 'Rich Text'
                name: 'richTextBlock'
                widget: 'object'
                summary: '{{fields.text}}' # Preview text in /admin
                fields:
                  - label: 'Rich Text'
                    name: 'richText'
                    widget: 'markdown'
                    required: false

              # Image
              - label: 'Image'
                name: 'imageBlock'
                widget: 'object'
                summary: '{{fields.alt}}'
                fields:
                  - label: 'Image'
                    name: 'image'
                    widget: 'image'
                    media_library:
                      config:
                        multiple: false
                  - label: 'Alt Text'
                    name: 'alt'
                    widget: 'string'
                    required: false
                  - label: 'Attribution'
                    name: 'attribution'
                    widget: 'text'
                    required: false

  - label: 'Resources'
    label_singular: 'Resource'
    name: 'resources'
    files:
      - label: 'Lorem Ipsum'
        name: 'lorem-ipsum'
        file: 'src/content/resources/lorem-ipsum.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - { label: 'Description', name: 'description', widget: 'formatted-text' }
          - label: 'Code'
            name: 'code'
            widget: 'select'
            options:
              - label: 'Science'
                value: 'sci'
              - label: 'Economics'
                value: 'eco'
              - label: 'Grammar'
                value: 'gra'
          - label: 'Color'
            name: 'color'
            widget: 'color'
            allow_input: true
          - label: 'Size'
            name: 'size'
            widget: 'select'
            options:
              - label: 'XS'
                value: 'xs'
              - label: 'S'
                value: 's'
              - label: 'M'
                value: 'm'
              - label: 'L'
                value: 'l'
              - label: 'XL'
                value: 'xl'
              - label: '2XL'
                value: '2xl'
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Price', name: 'price', widget: 'string' }
          - { label: 'Image Source', name: 'imageSrc', widget: 'string' }
          - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }

      - label: 'Cogito Ergo Sum'
        name: 'cogito-ergo-sum'
        file: 'src/content/resources/cogito-ergo-sum.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - { label: 'Description', name: 'description', widget: 'formatted-text' }
          - label: 'Code'
            name: 'code'
            widget: 'select'
            options:
              - label: 'Science'
                value: 'sci'
              - label: 'Economics'
                value: 'eco'
              - label: 'Grammar'
                value: 'gra'
          - label: 'Color'
            name: 'color'
            widget: 'color'
            allow_input: true
          - label: 'Size'
            name: 'size'
            widget: 'select'
            options:
              - label: 'XS'
                value: 'xs'
              - label: 'S'
                value: 's'
              - label: 'M'
                value: 'm'
              - label: 'L'
                value: 'l'
              - label: 'XL'
                value: 'xl'
              - label: '2XL'
                value: '2xl'
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Price', name: 'price', widget: 'string' }
          - { label: 'Image Source', name: 'imageSrc', widget: 'string' }
          - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }

      - label: 'Gratia Plena'
        name: 'gratia-plena'
        file: 'src/content/resources/gratia-plena.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - { label: 'Description', name: 'description', widget: 'formatted-text' }
          - label: 'Code'
            name: 'code'
            widget: 'select'
            options:
              - label: 'Science'
                value: 'sci'
              - label: 'Economics'
                value: 'eco'
              - label: 'Grammar'
                value: 'gra'
          - label: 'Color'
            name: 'color'
            widget: 'color'
            allow_input: true
          - label: 'Size'
            name: 'size'
            widget: 'select'
            options:
              - label: 'XS'
                value: 'xs'
              - label: 'S'
                value: 's'
              - label: 'M'
                value: 'm'
              - label: 'L'
                value: 'l'
              - label: 'XL'
                value: 'xl'
              - label: '2XL'
                value: '2xl'
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Price', name: 'price', widget: 'string' }
          - { label: 'Image Source', name: 'imageSrc', widget: 'string' }
          - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }

      - label: 'Deus Ex'
        name: 'deus-ex'
        file: 'src/content/resources/deus-ex.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - { label: 'Description', name: 'description', widget: 'formatted-text' }
          - label: 'Code'
            name: 'code'
            widget: 'select'
            options:
              - label: 'Science'
                value: 'sci'
              - label: 'Economics'
                value: 'eco'
              - label: 'Grammar'
                value: 'gra'
          - label: 'Color'
            name: 'color'
            widget: 'color'
            allow_input: true
          - label: 'Size'
            name: 'size'
            widget: 'select'
            options:
              - label: 'XS'
                value: 'xs'
              - label: 'S'
                value: 's'
              - label: 'M'
                value: 'm'
              - label: 'L'
                value: 'l'
              - label: 'XL'
                value: 'xl'
              - label: '2XL'
                value: '2xl'
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Price', name: 'price', widget: 'string' }
          - { label: 'Image Source', name: 'imageSrc', widget: 'string' }
          - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }

      - label: 'Libera Nos A Malo'
        name: 'libera-nos-a-malo'
        file: 'src/content/resources/libera-nos-a-malo.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - { label: 'Description', name: 'description', widget: 'formatted-text' }
          - label: 'Code'
            name: 'code'
            widget: 'select'
            options:
              - label: 'Science'
                value: 'sci'
              - label: 'Economics'
                value: 'eco'
              - label: 'Grammar'
                value: 'gra'
          - label: 'Color'
            name: 'color'
            widget: 'color'
            allow_input: true
          - label: 'Size'
            name: 'size'
            widget: 'select'
            options:
              - label: 'XS'
                value: 'xs'
              - label: 'S'
                value: 's'
              - label: 'M'
                value: 'm'
              - label: 'L'
                value: 'l'
              - label: 'XL'
                value: 'xl'
              - label: '2XL'
                value: '2xl'
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Price', name: 'price', widget: 'string' }
          - { label: 'Image Source', name: 'imageSrc', widget: 'string' }
          - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }

      - label: 'Fructus Ventris'
        name: 'fructus-ventris'
        file: 'src/content/resources/fructus-ventris.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - { label: 'Description', name: 'description', widget: 'formatted-text' }
          - label: 'Code'
            name: 'code'
            widget: 'select'
            options:
              - label: 'Science'
                value: 'sci'
              - label: 'Economics'
                value: 'eco'
              - label: 'Grammar'
                value: 'gra'
          - label: 'Color'
            name: 'color'
            widget: 'color'
            allow_input: true
          - label: 'Size'
            name: 'size'
            widget: 'select'
            options:
              - label: 'XS'
                value: 'xs'
              - label: 'S'
                value: 's'
              - label: 'M'
                value: 'm'
              - label: 'L'
                value: 'l'
              - label: 'XL'
                value: 'xl'
              - label: '2XL'
                value: '2xl'
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Price', name: 'price', widget: 'string' }
          - { label: 'Image Source', name: 'imageSrc', widget: 'string' }
          - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }

  - label: 'Resource Filters'
    label_singular: 'Resource Filter'
    name: 'resourceFilters'
    files:
      - label: 'Code'
        name: 'code'
        file: 'src/content/resourceFilters/code.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - label: 'Options'
            name: 'options'
            widget: 'list'
            fields:
              - { label: 'Value', name: 'value', widget: 'string' }
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Is Selected', name: 'isSelected', widget: 'boolean' }

      - label: 'Color'
        name: 'color'
        file: 'src/content/resourceFilters/color.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - label: 'Options'
            name: 'options'
            widget: 'list'
            fields:
              - { label: 'Value', name: 'value', widget: 'string' }
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Is Selected', name: 'isSelected', widget: 'boolean' }

      - label: 'Size'
        name: 'size'
        file: 'src/content/resourceFilters/size.yml'
        fields:
          - { label: 'ID', name: 'id', widget: 'string', required: true }
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, pattern: '^[a-z0-9-]+$' }
          - label: 'Options'
            name: 'options'
            widget: 'list'
            fields:
              - { label: 'Value', name: 'value', widget: 'string' }
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Is Selected', name: 'isSelected', widget: 'boolean' }

  - name: 'documents'
    label: 'Documents'
    folder: 'src/content/documents'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'formatted-text' }
      - { label: 'Page Ordering', name: 'order', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
